// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations"
    // seed: 'prisma/seed.js',

  },
  datasource: {
    url: "postgresql://postgres:1504@localhost:5432/volty?schema=public",
  },
});
