//npm install --save-dev @prisma/internals

// prisma.config.js
export default {
  datasources: {
    db: {
      url: "postgresql://postgres:1504@localhost:5432/volty?schema=public"
    }
  }
}

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// require('dotenv').config();

// module.exports = {
//   datasource: {
//     url: process.env.DATABASE_URL,
//   },
// };